<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ page isELIgnored='false'%>

<title>View Tree</title>


<div id="content">
<h3>View Tree</h3>

	<s:url action ="draw" id = "url1">
	</s:url>


	<fieldset >
		<legend>Image Parameters</legend>

		<s:form action="draw" method="get" >
				<s:textfield label="Height" name="height" value="%{getHeight()}"/>
				<s:textfield label="Width" name="width" value="%{getWidth()}"/>
				<s:textfield label="Outgroups" name="outgroups" value="%{outgroups}" maxlength="100"/>
			<s:submit value="Redraw"/>
		</s:form>
	</fieldset>

	<s:if test="%{!hasActionErrors() && !hasFieldErrors()}">
		<p>Click nodes to collapse/expand</p>

		<s:url id="streamurl" action="stream">
			<s:param name="location">tmptree</s:param> 
			<s:param name="inputPath"><s:property value="%{getImageMaker().getImageFileName()}"/></s:param> 
		</s:url>

		<img border="0" src="${streamurl}" alt="Tree" usemap="#treemap"/> 
		<map id="treemap" name="treemap">
			<s:iterator id="ni" value="%{getImageMaker().getNodeInfo()}">
				<s:url id="drawurl" action="draw" includeParams="get">
					<s:param name="collapse" value="${ni.collapse}"/>
				</s:url>
				<area shape="circle" coords="${ni.x}, ${ni.y},4" href="${drawurl}" />
			</s:iterator>
		</map>
	</s:if>

	<p>Image generated by: PHY·FI by Jakob Fredslund. Fredslund, J.  (2006)"PHY·FI:fast and easy online creation and manipulation of phylogeny color figures" BMC Bioinformatics7:315</p>



