#!/bin/sh

# Can't run module command (I think it's a bash fn) without sourcing bashrc
source $HOME/.bashrc

module load dppdiv/pll_1.0 
echo "CIPRES_THREADSPP=$CIPRES_THREADSPP"
echo "CIPRES_NP=$CIPRES_NP"
echo "running:"
echo "dppdiv-pthreads $*"

dppdiv-pthreads $*

