/*
 * AutoGeneratedKey.java
 */
package org.ngbw.sdk.database;


import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 * A thin container for a <code>Column</code> object that facilitates the retrieval of automatically
 * generated keys.
 * 
 * @author Paul Hoover
 *
 */
class AutoGeneratedKey extends SimpleKey {

	// constructors


	/**
	 * Constructs a container for the given <code>Column</code> object.
	 * 
	 * @param key
	 */
	AutoGeneratedKey(Column<?> key)
	{
		super(key);
	}


	// public methods


	/**
	 * Retrieves an automatically generated key from a <code>Statement</code> object.
	 * 
	 * @param statement the <code>Statement</code> object whose execution produced the key
	 * @throws IOException
	 * @throws SQLException
	 */
	public void getGeneratedKeys(Statement statement) throws IOException, SQLException
	{
		ResultSet newKey = statement.getGeneratedKeys();

		try {
			if (newKey.next())
				m_key.assignValue(newKey, 1);
		}
		finally {
			newKey.close();
		}
	}
}
